#open data base
import unittest
from tkinter import *
import sqlite3
import tkinter as tk
ADMINNAME="Admin"
ADMINPASSWORD="Admin"


def OpenData():
    
    def Board_Data():

        conn = sqlite3.connect("Boards.db")
        cursor = conn.cursor()
        cursor.execute("CREATE TABLE IF NOT EXISTS " + "'" + ADMINNAME + "'" + " ('Serial_number' FLOAT, 'Description' TEXT, 'Image_location' TEXT)")
        if cursor.fetchone() is None:
            global software_path
            while software_path[-8:]!="COMMU.py":
                software_path = filedialog.askopenfilename(initialdir=r"C:\Desktop\Com", title = "בחר קובץ התקנה", filetypes = (("installation", "*COMMU.py"), ))
            software_path=software_path[:-8]
#####Settings_1

            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (0, "הגדרות", r""+software_path+"Default/Tools/settings.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (0.01, "הוספ", r""+software_path+"Default/Tools/add.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (0.02, "מחיק", r""+software_path+"Default/Tools/delete.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (0.03, "התנתקות", r""+software_path+"Default/Tools/board log out.png"))
            conn.commit()
#
#####Emotions_1
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1, "רגשות", r""+software_path+"Default/Emotions/emotions.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.01, "עצבני", r""+software_path+"Default/Emotions/angry.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.02, "כועס", r""+software_path+"Default/Emotions/angry1.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.03, "משועמם", r""+software_path+"Default/Emotions/bored.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.04, "עצוב", r""+software_path+"Default/Emotions/crying.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.05, "בוכה", r""+software_path+"Default/Emotions/crying1.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.06, "חמוד", r""+software_path+"Default/Emotions/cute.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.07, "נבוך", r""+software_path+"Default/Emotions/embarrassed.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.08, "שמח", r""+software_path+"Default/Emotions/happy.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.09, "צוחק", r""+software_path+"Default/Emotions/happy1.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.10, "מאושר", r""+software_path+"Default/Emotions/happy2.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.11, "מחייך", r""+software_path+"Default/Emotions/happy3.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.12, "מאוהב", r""+software_path+"Default/Emotions/in-love.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.13, "נשיקה", r""+software_path+"Default/Emotions/kiss.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.14, "מתפקע", r""+software_path+"Default/Emotions/laughing.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.15, "מדוכדך", r""+software_path+"Default/Emotions/sad.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.16, "רוגז", r""+software_path+"Default/Emotions/sad1.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.17, "חולה", r""+software_path+"Default/Emotions/sick.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.18, "ישנוני", r""+software_path+"Default/Emotions/sleepy.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.19, "שובב", r""+software_path+"Default/Emotions/tongue.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (1.20, "קורץ", r""+software_path+"Default/Emotions/wink.png"))
            conn.commit()
#
#####Food_2
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2, "אוכל", r""+software_path+"Default/Food/food.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.01, "תפוח", r""+software_path+"Default/Food/apple.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.02, "בננות", r""+software_path+"Default/Food/bananas.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.03, "גזר", r""+software_path+"Default/Food/carrot.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.04, "דובדבן", r""+software_path+"Default/Food/cherry.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.05, "שוק עוף", r""+software_path+"Default/Food/chicken-leg.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.06, "שוקולד", r""+software_path+"Default/Food/chocolate.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.07, "עוגיה", r""+software_path+"Default/Food/cookie.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.08, "תירס", r""+software_path+"Default/Food/corn.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.09, "קרואסון", r""+software_path+"Default/Food/croissant.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.10, "קאפקייק", r""+software_path+"Default/Food/cupcake.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.11, "דונאט", r""+software_path+"Default/Food/donut.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.12, "צ'יפס", r""+software_path+"Default/Food/french-fries.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.13, "ביצת עין", r""+software_path+"Default/Food/fried-egg.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.14, "ענבים", r""+software_path+"Default/Food/grapes.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.15, "המבורגר", r""+software_path+"Default/Food/hamburger.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.16, "נקניקיה בלחמניה", r""+software_path+"Default/Food/hot-dog.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.17, "גלידה", r""+software_path+"Default/Food/ice-cream.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.18, "קטשופ", r""+software_path+"Default/Food/ketchup.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.19, "מילקשייק", r""+software_path+"Default/Food/milkshake.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.20, "תפוז", r""+software_path+"Default/Food/orange.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.21, "אפרסק", r""+software_path+"Default/Food/peach.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.22, "אגס", r""+software_path+"Default/Food/pear.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.23, "פיצה", r""+software_path+"Default/Food/pizza.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.24, "ארטיק", r""+software_path+"Default/Food/popsicle.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.25, "משקה מוגז", r""+software_path+"Default/Food/soda.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.26, "תות", r""+software_path+"Default/Food/strawberry.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.27, "צנים", r""+software_path+"Default/Food/toast.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (2.28, "אבטיח", r""+software_path+"Default/Food/watermelon.png"))
            conn.commit()
#
#####Outdoor_Activities_3                
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (3, "פעילויות חוץ", r""+software_path+"Default/Outdoor-Activities/outdoor-activities.png"))
            conn.commit()
#
#####Home_4                
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4, "פעילויות בית", r""+software_path+"Default/Home/home.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.01, "מסרק", r""+software_path+"Default/Home/comb.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.02, "מחשב", r""+software_path+"Default/Home/computer.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.03, "ברווז אמבט", r""+software_path+"Default/Home/duck.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.04, "מנורה", r""+software_path+"Default/Home/light-bulb.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.05, "סמארטפון", r""+software_path+"Default/Home/mobile-phone.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.06, "מקלחת", r""+software_path+"Default/Home/shower.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.07, "קירור", r""+software_path+"Default/Home/temperature.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.08, "חימום", r""+software_path+"Default/Home/temperature-hot.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.09, "אסלה", r""+software_path+"Default/Home/toilet.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.10, "לצחצח שיניים", r""+software_path+"Default/Home/toothbrush.png"))
            conn.commit()
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (4.11, "חלון", r""+software_path+"Default/Home/window.png"))
            conn.commit()
#
#####Colors_5                
            cursor.execute("INSERT INTO  "  + ADMINNAME +  " ('Serial_number', 'Description', 'Image_location') VALUES (?,?,?)", (5, "צבעים", r""+software_path+"Default/Colors/colors.png"))
            conn.commit()

            
    conn = sqlite3.connect("Accounts.db")
    cursor = conn.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS 'Users' ('User_Name' TEXT, 'Password' TEXT, 'First_Name' TEXT, 'Last_Name' TEXT, 'User_Type' TEXT)")
    cursor.execute("SELECT * FROM 'Users' WHERE `User_Name` = " + "'" + ADMINNAME + "'" + " AND `Password` = " + "'" + ADMINPASSWORD + "'")
    if cursor.fetchone() is None:
        cursor.execute("INSERT INTO  'Users' ('User_Name', 'Password', 'First_Name', 'Last_Name', 'User_Type') VALUES (?,?,?,?,?)", (ADMINNAME, ADMINPASSWORD, "Administrator","Administrator","Admin"))
        conn.commit()
        Board_Data()

